name: deploy
on:
  push:
    branches:
      - development
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i
      - run: npm run build
      - run: npx gh-pages -d public -b test -u "Omer Dolev <omerdolev90@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}