name: deploy
on: [push]
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i
      - run: npm run build
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/dolevoper/dolevoper.github.io.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx gh-pages -d public -u "Omer Dolev <omerdolev90@gmail.com>"